main: smp.edgecraft.uhc.core.UHCCore
name: UHCCore
version: 0.0.0.1
author: CJMinecraft
authors: [CJMinecraft, Dogatron03, ImJustIsabella, Prowdz, bkYT]
description: The core gameplay for a UHC
api-version: 1.13
commands:
  uhc:
    description: The main command for the UHC
    usage: /uhc
permissions:
  uhc.link:
    description: Link a discord user with a minecraft account
    default: true
  uhc.prepare:
    description: Prepare the teams
    default: op
  uhc.spectate:
    description: Join the spectator team
    default: true
  uhc.start:
    description: Start the UHC
    default: op
  uhc.team:
    description: Manually set a player's team
    default: op
  uhc.update:
    description: Update the plugin
    default: op